=== andrewmherren/surface_kali/live_build/config/includes.chroot/etc/btscanner.dtd
<!--
 * btscanner.dtd
-->

<!ELEMENT btscanner (files,rangedef+)>

<!--
 * files: the list of config/resource files
-->
<!ELEMENT files (log,oui,store)>

<!--
 * log: the log file
-->
<!ELEMENT log (#PCDATA)>

<!--
 * oui: the oui database
-->
<!ELEMENT oui (#PCDATA)>

<!--
 * store: where the store the details of found items
-->
<!ELEMENT store (#PCDATA)>



<!--
 * rangedef. for each range address, tell the slave what to do.
 * needs start and end range. with 
-->
<!ELEMENT rangedef (vulnerabilities, name?,hci?,rssi?,lq?,txpwr?,sdp?)>
<!ATTLIST rangedef start CDATA #REQUIRED
                   end   CDATA #REQUIRED>


<!--
 * list of services/inforations for a rangedef function
-->
<!ELEMENT vulnerabilities (#PCDATA)>
<!ELEMENT name EMPTY>
<!ELEMENT hci EMPTY>
<!ELEMENT rssi EMPTY>
<!ELEMENT lq EMPTY>
<!ELEMENT txpwr EMPTY>
<!ELEMENT sdp EMPTY>

=== andrewmherren/surface_kali/live_build/config/includes.chroot/etc/btscanner.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE btscanner SYSTEM "file:///etc/btscanner.dtd">
<btscanner>
<files>
	<log>btscanner.log</log>
	<oui>/usr/share/btscanner/oui.txt</oui>
	<store>~/bts</store>
</files>

<!-- Global range -->
<rangedef start="00:00:00:00:00:00" end="FF:FF:FF:FF:FF:FF">
	<vulnerabilities/>
	<name/>
	<hci/>
</rangedef>

<!-- Nokia 6310i range 1 -->
<rangedef start="00:60:57:00:00:00" end="00:60:57:FF:FF:FF">
	<vulnerabilities>Snarf</vulnerabilities>
	<name/>
	<hci/>
	<rssi/>
	<lq/>
	<txpwr/>
	<sdp/>
</rangedef>
<!-- Nokia 6310i range 2 -->
<rangedef start="00:0E:6D:00:00:00" end="00:0E:6D:FF:FF:FF">
	<vulnerabilities>Snarf</vulnerabilities>
	<name/>
	<hci/>
	<rssi/>
	<lq/>
	<txpwr/>
	<sdp/>
</rangedef>
<!-- Nokia 6310i range 3 -->
<rangedef start="00:02:EE:00:00:00" end="00:02:EE:FF:FF:FF">
	<vulnerabilities>Snarf</vulnerabilities>
	<name/>
	<hci/>
	<rssi/>
	<lq/>
	<txpwr/>
	<sdp/>
</rangedef>

<!-- Nokia 6230 range 1 -->
<rangedef start="00:E0:03:00:00:00" end="00:E0:03:FF:FF:FF">
	<vulnerabilities>Snarf</vulnerabilities>
	<name/>
	<hci/>
	<rssi/>
	<lq/>
	<txpwr/>
	<sdp/>
</rangedef>

<!-- Sony Ericsson T610 range 1 -->
<rangedef start="00:0E:07:00:00:00" end="00:0E:07:FF:FF:FF">
	<vulnerabilities>Snarf</vulnerabilities>
	<name/>
	<hci/>
	<rssi/>
	<lq/>
	<txpwr/>
	<sdp/>
</rangedef>
<!-- Sony Ericsson T610 (also others) range 2 -->
<rangedef start="00:0A:D9:00:00:00" end="00:0A:D9:FF:FF:FF">
	<vulnerabilities>Snarf</vulnerabilities>
	<name/>
	<hci/>
	<rssi/>
	<lq/>
	<txpwr/>
	<sdp/>
</rangedef>

</btscanner>
